global:
  topic: TopicTest
  consumer:
    broadcasting:
      group: test-consume-broadcasting-group
    clustering:
      group: test-consume-clustering-group

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: test-send-normal-group
